In [2]:
# 以下のライブラリをあらかじめ読み込む
import numpy as np
import numpy.random as random
import scipy as sp
# 線形代数用ライブラリ
import scipy.linalg as linalg
# 最適化計算（最小値）用のライブラリ
from scipy.optimize import minimize_scalar
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 少数第３位まで表示
%precision 3

'%.3f'

In [12]:
# Numpyの基礎
## 配列の作成
data = np.array([[1, 2, 3, 9, 2], [7, 4, 10, 6, 7], [1, 2, 3, 4, 5]])
data

array([[ 1,  2,  3,  9,  2],
       [ 7,  4, 10,  6,  7],
       [ 1,  2,  3,  4,  5]])

In [13]:
# データの型
data.dtype

dtype('int64')

In [14]:
print("次元数:", data.ndim)
print("要素数:", data.size)

次元数: 2
要素数: 15


In [17]:
# 全ての要素に対する計算
data + 100
data * 100

array([[ 100,  200,  300,  900,  200],
       [ 700,  400, 1000,  600,  700],
       [ 100,  200,  300,  400,  500]])

In [20]:
# ソート
data.sort()
print("ソート後:", data)

ソート後: [[ 1  2  2  3  9]
 [ 4  6  7  7 10]
 [ 1  2  3  4  5]]


In [26]:
data[::1][::-1].sort()
data

array([[ 1,  2,  2,  3,  9],
       [ 4,  6,  7,  7, 10],
       [ 1,  2,  3,  4,  5]])

In [31]:
print("min:", data.min())
print("max:", data.max())
print("sum:", data.sum())
print("cum:", data.cumsum()) # 積み上げ
print("ratio:", data.cumsum() / data.sum()) # 積み上げ割合

min: 1
max: 10
sum: 66
cum: [ 1  3  5  8 17 21 27 34 41 51 52 54 57 61 66]
ratio: [0.015 0.045 0.076 0.121 0.258 0.318 0.409 0.515 0.621 0.773 0.788 0.818
 0.864 0.924 1.   ]


In [67]:
## 乱数
random.seed(0)

# 正規分布（平均0, 分散1）の乱数を10個生成
rnd_data = random.randn(10)
print("乱数１０個の配列:", rnd_data)

乱数１０個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [52]:
## 抽出
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

# ランダム抽出
# １０個を抽出（重複あり、復元抽出）
random.choice(data, 10)

# １０個を抽出（重複なし、非復元抽出）
random.choice(data, 10, replace = False)

array([10,  1,  2,  9,  6,  3,  7,  4,  8,  5])

In [78]:
## 行列
array1 = np.arange(9).reshape(3, 3)
print(array1)

# 1行目
print(array1[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [81]:
## 行列の計算
array2 = np.arange(9, 18).reshape(3, 3)

# 行列の積
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [88]:
print(np.zeros((2, 3), dtype = np.int32))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [96]:
## Practice

### 2-1 OK
print(np.arange(1, 50).sum())

### 2-2 OK 
random.seed(1)
rnd_data = random.randn(10)
print("data:", rnd_data)
print("min:", rnd_data.min())
print("max:", rnd_data.max())
print("sum:", rnd_data.sum())

### 2-3 Re:OK
np.ones((5, 5), np.int32) * 3 ** 2 # fail

matrix = np.ones((5, 5), np.int32) * 3
np.dot(matrix, matrix) # right

1225
data: [ 1.624 -0.612 -0.528 -1.073  0.865 -2.302  1.745 -0.761  0.319 -0.249]
min: -2.3015386968802827
max: 1.74481176421648
sum: -0.9714089080609984


array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]], dtype=int32)

In [8]:
# Scipy Basics
matrix = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

# 行列式
print('行列式')
print(linalg.det(matrix))

# 逆行列
print('逆行列')
print(linalg.inv(matrix))

# 固有値と固有ベクトル
eig_value, eig_vector = linalg.eig(matrix)
print('固有値')
print(eig_value)
print('固有ベクトル')
print(eig_vector)

行列式
-4.0
逆行列
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]
固有値
[-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル
[[ 0.577  0.816  0.408]
 [ 0.577 -0.408 -0.816]
 [ 0.577 -0.408  0.408]]


In [16]:
## ニュートン法
def my_function(x):
    return (x ** 2 + 6 * x + 9)

# ライブラリ読み込み
from scipy.optimize import newton

# ニュートン法で計算
print(newton(my_function, 0))

# Brent法で最小値を求める計算実行
print(minimize_scalar(my_function, method = 'Brent'))

-2.999999976409712
     fun: 0.0
    nfev: 10
     nit: 4
 success: True
       x: -3.0000000000000004


In [21]:
# Prictice
## 2-4
matrix = np.array([[1, 2, 3], [1, 3, 2], [3, 1, 2]])
print('行列式', linalg.det(matrix))

## 2-5
print('逆行列', linalg.inv(matrix))
eig_value, eig_vector = linalg.eig(matrix)
print('固有値', eig_value)
print('固有ベクトル', eig_vector)

## 2-6
def my_function2(x):
    return x ** 3 + 2 * x + 1

print('ニュートン法', newton(my_function2, 0))

行列式 -12.000000000000002
逆行列 [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値 [ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル [[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]
ニュートン法 -0.4533976515164037


In [8]:
## Pandas Basics
# Series
sample_pandas_data = Series([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
print(sample_pandas_data)

indexed_data = Series([0, 10, 20, 30, 40, 50, 60, 70, 80, 90], index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(indexed_data)

print('データの値', indexed_data.values)
print('インデックスの値', indexed_data.index)


0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64
a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64
データの値 [ 0 10 20 30 40 50 60 70 80 90]
インデックスの値 Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')


In [16]:
attri_data1 = {
    'ID': ['101', '102', '103', '104', '105'],
    'City': ['Tokyo', 'Osaka', 'Kyoto', 'Hokkaido', 'Tokyo'],
    'Birth_Year': [1990, 1989, 1992, 1997, 1982],
    'Name': ['Hiroshi', 'Akiko', 'Yuki', 'Satoru', 'Steve'],
}

attri_data_frame1 = DataFrame(attri_data1, index = ['a', 'b', 'c', 'd', 'e'])

attri_data_frame1

ID      City  Birth_Year     Name
a  101     Tokyo        1990  Hiroshi
b  102     Osaka        1989    Akiko
c  103     Kyoto        1992     Yuki
d  104  Hokkaido        1997   Satoru
e  105     Tokyo        1982    Steve

In [19]:
# 転置
attri_data_frame1.T

a      b      c         d      e
ID              101    102    103       104    105
City          Tokyo  Osaka  Kyoto  Hokkaido  Tokyo
Birth_Year     1990   1989   1992      1997   1982
Name        Hiroshi  Akiko   Yuki    Satoru  Steve

In [22]:
# 列名の指定（一つの場合）
attri_data_frame1.Birth_Year

a    1990
b    1989
c    1992
d    1997
e    1982
Name: Birth_Year, dtype: int64

In [25]:
# 列名の指定（複数）
attri_data_frame1[['Name', 'Birth_Year']].T

a      b     c       d      e
Name        Hiroshi  Akiko  Yuki  Satoru  Steve
Birth_Year     1990   1989  1992    1997   1982

In [31]:
# 抽出
print(attri_data_frame1['City'] == 'Tokyo')
attri_data_frame1[attri_data_frame1['City'] == 'Tokyo']

a     True
b    False
c    False
d    False
e     True
Name: City, dtype: bool


ID   City  Birth_Year     Name
a  101  Tokyo        1990  Hiroshi
e  105  Tokyo        1982    Steve

In [38]:
# Try
## Birth_Yearが190以下
print(attri_data_frame1['Birth_Year'] <= 1990)
attri_data_frame1[attri_data_frame1['Birth_Year'] <= 1990]

## IDが103より大きい
print(attri_data_frame1['ID'] > '103')
attri_data_frame1[attri_data_frame1['ID'] > '103']

a     True
b     True
c    False
d    False
e     True
Name: Birth_Year, dtype: bool
a    False
b    False
c    False
d     True
e     True
Name: ID, dtype: bool


ID      City  Birth_Year    Name
d  104  Hokkaido        1997  Satoru
e  105     Tokyo        1982   Steve

In [43]:
## delete

# remove column
attri_data_frame1.drop(['Birth_Year'], axis = 1)
# remove row
attri_data_frame1.drop(['a', 'b', 'd'], axis = 0)

ID   City  Birth_Year   Name
c  103  Kyoto        1992   Yuki
e  105  Tokyo        1982  Steve

In [45]:
# join
attri_data2 = {
    'ID': ['100', '101', '102', '105', '107'],
    'Math': [50, 43, 33, 76, 98],
    'English': [90, 30, 20, 50, 30],
    'Sex': ['M', 'F', 'F', 'M', 'M'],
}

attri_data_frame2 = DataFrame(attri_data2)
attri_data_frame2

ID  Math  English Sex
0  100    50       90   M
1  101    43       30   F
2  102    33       20   F
3  105    76       50   M
4  107    98       30   M

In [46]:
## merge
# データのマージ
pd.merge(attri_data_frame1, attri_data_frame2)

ID   City  Birth_Year     Name  Math  English Sex
0  101  Tokyo        1990  Hiroshi    43       30   F
1  102  Osaka        1989    Akiko    33       20   F
2  105  Tokyo        1982    Steve    76       50   M

In [50]:
## aggregation
attri_data_frame2.groupby('Sex')['Math'].mean() # 平均

Sex
F    38.000000
M    74.666667
Name: Math, dtype: float64

In [52]:
# try
print('英語平均', attri_data_frame2.groupby('Sex')['English'].mean())

print('英語最大', attri_data_frame2.groupby('Sex')['English'].max())
print('英語最小', attri_data_frame2.groupby('Sex')['English'].min())

英語平均 Sex
F    25.000000
M    56.666667
Name: English, dtype: float64
英語最大 Sex
F    30
M    90
Name: English, dtype: int64
英語最小 Sex
F    20
M    30
Name: English, dtype: int64
