In [4]:
# 以下のライブラリをあらかじめ読み込む
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 少数第３位まで表示
%precision 3

'%.3f'

In [12]:
# Numpyの基礎
## 配列の作成
data = np.array([[1, 2, 3, 9, 2], [7, 4, 10, 6, 7], [1, 2, 3, 4, 5]])
data

array([[ 1,  2,  3,  9,  2],
       [ 7,  4, 10,  6,  7],
       [ 1,  2,  3,  4,  5]])

In [13]:
# データの型
data.dtype

dtype('int64')

In [14]:
print("次元数:", data.ndim)
print("要素数:", data.size)

次元数: 2
要素数: 15


In [17]:
# 全ての要素に対する計算
data + 100
data * 100

array([[ 100,  200,  300,  900,  200],
       [ 700,  400, 1000,  600,  700],
       [ 100,  200,  300,  400,  500]])

In [20]:
# ソート
data.sort()
print("ソート後:", data)

ソート後: [[ 1  2  2  3  9]
 [ 4  6  7  7 10]
 [ 1  2  3  4  5]]


In [26]:
data[::1][::-1].sort()
data

array([[ 1,  2,  2,  3,  9],
       [ 4,  6,  7,  7, 10],
       [ 1,  2,  3,  4,  5]])

In [31]:
print("min:", data.min())
print("max:", data.max())
print("sum:", data.sum())
print("cum:", data.cumsum()) # 積み上げ
print("ratio:", data.cumsum() / data.sum()) # 積み上げ割合

min: 1
max: 10
sum: 66
cum: [ 1  3  5  8 17 21 27 34 41 51 52 54 57 61 66]
ratio: [0.015 0.045 0.076 0.121 0.258 0.318 0.409 0.515 0.621 0.773 0.788 0.818
 0.864 0.924 1.   ]


In [67]:
## 乱数
random.seed(0)

# 正規分布（平均0, 分散1）の乱数を10個生成
rnd_data = random.randn(10)
print("乱数１０個の配列:", rnd_data)

乱数１０個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [52]:
## 抽出
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

# ランダム抽出
# １０個を抽出（重複あり、復元抽出）
random.choice(data, 10)

# １０個を抽出（重複なし、非復元抽出）
random.choice(data, 10, replace = False)

array([10,  1,  2,  9,  6,  3,  7,  4,  8,  5])

In [78]:
## 行列
array1 = np.arange(9).reshape(3, 3)
print(array1)

# 1行目
print(array1[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [81]:
## 行列の計算
array2 = np.arange(9, 18).reshape(3, 3)

# 行列の積
np.dot(array1, array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [88]:
print(np.zeros((2, 3), dtype = np.int32))
print(np.ones((2, 3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [96]:
## Practice

### 2-1 OK
print(np.arange(1, 50).sum())

### 2-2 OK 
random.seed(1)
rnd_data = random.randn(10)
print("data:", rnd_data)
print("min:", rnd_data.min())
print("max:", rnd_data.max())
print("sum:", rnd_data.sum())

### 2-3 Re:OK
np.ones((5, 5), np.int32) * 3 ** 2 # fail

matrix = np.ones((5, 5), np.int32) * 3
np.dot(matrix, matrix) # right

1225
data: [ 1.624 -0.612 -0.528 -1.073  0.865 -2.302  1.745 -0.761  0.319 -0.249]
min: -2.3015386968802827
max: 1.74481176421648
sum: -0.9714089080609984


array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]], dtype=int32)